package ch.ethz.coss.nervousnet.vm.storage;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;
import ch.ethz.coss.nervousnet.vm.storage.ConnectivityData;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONNECTIVITY_DATA".
*/
public class ConnectivityDataDao extends AbstractDao<ConnectivityData, Long> {

    public static final String TABLENAME = "CONNECTIVITY_DATA";

    /**
     * Properties of entity ConnectivityData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TimeStamp = new Property(1, Long.class, "TimeStamp", false, "TIME_STAMP");
        public final static Property IsConnected = new Property(2, Boolean.class, "isConnected", false, "IS_CONNECTED");
        public final static Property NetworkType = new Property(3, Integer.class, "networkType", false, "NETWORK_TYPE");
        public final static Property IsRoaming = new Property(4, Boolean.class, "isRoaming", false, "IS_ROAMING");
        public final static Property WifiHashId = new Property(5, String.class, "wifiHashId", false, "WIFI_HASH_ID");
        public final static Property WifiStrength = new Property(6, Integer.class, "wifiStrength", false, "WIFI_STRENGTH");
        public final static Property MobileHashId = new Property(7, String.class, "mobileHashId", false, "MOBILE_HASH_ID");
        public final static Property Volatility = new Property(8, long.class, "Volatility", false, "VOLATILITY");
        public final static Property ShareFlag = new Property(9, Boolean.class, "ShareFlag", false, "SHARE_FLAG");
    };


    public ConnectivityDataDao(DaoConfig config) {
        super(config);
    }
    
    public ConnectivityDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONNECTIVITY_DATA\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TIME_STAMP\" INTEGER," + // 1: TimeStamp
                "\"IS_CONNECTED\" INTEGER," + // 2: isConnected
                "\"NETWORK_TYPE\" INTEGER," + // 3: networkType
                "\"IS_ROAMING\" INTEGER," + // 4: isRoaming
                "\"WIFI_HASH_ID\" TEXT," + // 5: wifiHashId
                "\"WIFI_STRENGTH\" INTEGER," + // 6: wifiStrength
                "\"MOBILE_HASH_ID\" TEXT," + // 7: mobileHashId
                "\"VOLATILITY\" INTEGER NOT NULL ," + // 8: Volatility
                "\"SHARE_FLAG\" INTEGER);"); // 9: ShareFlag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONNECTIVITY_DATA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ConnectivityData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long TimeStamp = entity.getTimeStamp();
        if (TimeStamp != null) {
            stmt.bindLong(2, TimeStamp);
        }
 
        Boolean isConnected = entity.getIsConnected();
        if (isConnected != null) {
            stmt.bindLong(3, isConnected ? 1L: 0L);
        }
 
        Integer networkType = entity.getNetworkType();
        if (networkType != null) {
            stmt.bindLong(4, networkType);
        }
 
        Boolean isRoaming = entity.getIsRoaming();
        if (isRoaming != null) {
            stmt.bindLong(5, isRoaming ? 1L: 0L);
        }
 
        String wifiHashId = entity.getWifiHashId();
        if (wifiHashId != null) {
            stmt.bindString(6, wifiHashId);
        }
 
        Integer wifiStrength = entity.getWifiStrength();
        if (wifiStrength != null) {
            stmt.bindLong(7, wifiStrength);
        }
 
        String mobileHashId = entity.getMobileHashId();
        if (mobileHashId != null) {
            stmt.bindString(8, mobileHashId);
        }
        stmt.bindLong(9, entity.getVolatility());
 
        Boolean ShareFlag = entity.getShareFlag();
        if (ShareFlag != null) {
            stmt.bindLong(10, ShareFlag ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ConnectivityData readEntity(Cursor cursor, int offset) {
        ConnectivityData entity = new ConnectivityData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // TimeStamp
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // isConnected
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // networkType
            cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0, // isRoaming
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // wifiHashId
            cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6), // wifiStrength
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // mobileHashId
            cursor.getLong(offset + 8), // Volatility
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0 // ShareFlag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ConnectivityData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTimeStamp(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIsConnected(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setNetworkType(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setIsRoaming(cursor.isNull(offset + 4) ? null : cursor.getShort(offset + 4) != 0);
        entity.setWifiHashId(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setWifiStrength(cursor.isNull(offset + 6) ? null : cursor.getInt(offset + 6));
        entity.setMobileHashId(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setVolatility(cursor.getLong(offset + 8));
        entity.setShareFlag(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ConnectivityData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ConnectivityData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
