package ch.ethz.coss.nervousnet.vm.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ch.ethz.coss.nervousnet.vm.model.AccelData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ACCEL_DATA".
*/
public class AccelDataDao extends AbstractDao<AccelData, Long> {

    public static final String TABLENAME = "ACCEL_DATA";

    /**
     * Properties of entity AccelData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property TimeStamp = new Property(0, long.class, "TimeStamp", true, "TIME_STAMP");
        public final static Property X = new Property(1, Float.class, "X", false, "X");
        public final static Property Y = new Property(2, Float.class, "Y", false, "Y");
        public final static Property Z = new Property(3, Float.class, "Z", false, "Z");
        public final static Property Volatility = new Property(4, long.class, "Volatility", false, "VOLATILITY");
        public final static Property ShareFlag = new Property(5, Boolean.class, "ShareFlag", false, "SHARE_FLAG");
    };


    public AccelDataDao(DaoConfig config) {
        super(config);
    }
    
    public AccelDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ACCEL_DATA\" (" + //
                "\"TIME_STAMP\" INTEGER PRIMARY KEY NOT NULL ," + // 0: TimeStamp
                "\"X\" REAL," + // 1: X
                "\"Y\" REAL," + // 2: Y
                "\"Z\" REAL," + // 3: Z
                "\"VOLATILITY\" INTEGER NOT NULL ," + // 4: Volatility
                "\"SHARE_FLAG\" INTEGER);"); // 5: ShareFlag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ACCEL_DATA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, AccelData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTimeStamp());
 
        Float X = entity.getX();
        if (X != null) {
            stmt.bindDouble(2, X);
        }
 
        Float Y = entity.getY();
        if (Y != null) {
            stmt.bindDouble(3, Y);
        }
 
        Float Z = entity.getZ();
        if (Z != null) {
            stmt.bindDouble(4, Z);
        }
        stmt.bindLong(5, entity.getVolatility());
 
        Boolean ShareFlag = entity.getShareFlag();
        if (ShareFlag != null) {
            stmt.bindLong(6, ShareFlag ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public AccelData readEntity(Cursor cursor, int offset) {
        AccelData entity = new AccelData( //
            cursor.getLong(offset + 0), // TimeStamp
            cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1), // X
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // Y
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // Z
            cursor.getLong(offset + 4), // Volatility
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // ShareFlag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, AccelData entity, int offset) {
        entity.setTimeStamp(cursor.getLong(offset + 0));
        entity.setX(cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1));
        entity.setY(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
        entity.setZ(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setVolatility(cursor.getLong(offset + 4));
        entity.setShareFlag(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(AccelData entity, long rowId) {
        entity.setTimeStamp(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(AccelData entity) {
        if(entity != null) {
            return entity.getTimeStamp();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
