package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BATTERY_READING".
 */
public class BatteryReading extends SensorReading  {

    /** Not-null value. */
    private java.util.Date TimeStamp;
    private Float Percent;
    private Byte ChargingType;
    private Byte Health;
    private Float Temperature;
    private Integer Volt;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BatteryReading() {
    }

    public BatteryReading(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public BatteryReading(java.util.Date TimeStamp, Float Percent, Byte ChargingType, Byte Health, Float Temperature, Integer Volt) {
        this.TimeStamp = TimeStamp;
        this.Percent = Percent;
        this.ChargingType = ChargingType;
        this.Health = Health;
        this.Temperature = Temperature;
        this.Volt = Volt;
    }

    /** Not-null value. */
    public java.util.Date getTimeStamp() {
        return TimeStamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimeStamp(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public Float getPercent() {
        return Percent;
    }

    public void setPercent(Float Percent) {
        this.Percent = Percent;
    }

    public Byte getChargingType() {
        return ChargingType;
    }

    public void setChargingType(Byte ChargingType) {
        this.ChargingType = ChargingType;
    }

    public Byte getHealth() {
        return Health;
    }

    public void setHealth(Byte Health) {
        this.Health = Health;
    }

    public Float getTemperature() {
        return Temperature;
    }

    public void setTemperature(Float Temperature) {
        this.Temperature = Temperature;
    }

    public Integer getVolt() {
        return Volt;
    }

    public void setVolt(Integer Volt) {
        this.Volt = Volt;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
