package ch.ethz.coss.nervousnet.vm.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ch.ethz.coss.nervousnet.vm.model.BeaconData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BEACON_DATA".
*/
public class BeaconDataDao extends AbstractDao<BeaconData, Long> {

    public static final String TABLENAME = "BEACON_DATA";

    /**
     * Properties of entity BeaconData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property TimeStamp = new Property(0, long.class, "TimeStamp", true, "TIME_STAMP");
        public final static Property Rssi = new Property(1, Integer.class, "rssi", false, "RSSI");
        public final static Property Mac = new Property(2, Long.class, "mac", false, "MAC");
        public final static Property AdvertisementMSB = new Property(3, Long.class, "advertisementMSB", false, "ADVERTISEMENT_MSB");
        public final static Property AdvertisementLSB = new Property(4, Long.class, "advertisementLSB", false, "ADVERTISEMENT_LSB");
        public final static Property BleuuidMSB = new Property(5, Long.class, "bleuuidMSB", false, "BLEUUID_MSB");
        public final static Property BleuuidLSB = new Property(6, Long.class, "bleuuidLSB", false, "BLEUUID_LSB");
        public final static Property Major = new Property(7, Integer.class, "major", false, "MAJOR");
        public final static Property Minor = new Property(8, Integer.class, "minor", false, "MINOR");
        public final static Property Txpower = new Property(9, Integer.class, "txpower", false, "TXPOWER");
        public final static Property Volatility = new Property(10, long.class, "Volatility", false, "VOLATILITY");
        public final static Property ShareFlag = new Property(11, Boolean.class, "ShareFlag", false, "SHARE_FLAG");
    };


    public BeaconDataDao(DaoConfig config) {
        super(config);
    }
    
    public BeaconDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BEACON_DATA\" (" + //
                "\"TIME_STAMP\" INTEGER PRIMARY KEY NOT NULL ," + // 0: TimeStamp
                "\"RSSI\" INTEGER," + // 1: rssi
                "\"MAC\" INTEGER," + // 2: mac
                "\"ADVERTISEMENT_MSB\" INTEGER," + // 3: advertisementMSB
                "\"ADVERTISEMENT_LSB\" INTEGER," + // 4: advertisementLSB
                "\"BLEUUID_MSB\" INTEGER," + // 5: bleuuidMSB
                "\"BLEUUID_LSB\" INTEGER," + // 6: bleuuidLSB
                "\"MAJOR\" INTEGER," + // 7: major
                "\"MINOR\" INTEGER," + // 8: minor
                "\"TXPOWER\" INTEGER," + // 9: txpower
                "\"VOLATILITY\" INTEGER NOT NULL ," + // 10: Volatility
                "\"SHARE_FLAG\" INTEGER);"); // 11: ShareFlag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BEACON_DATA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BeaconData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTimeStamp());
 
        Integer rssi = entity.getRssi();
        if (rssi != null) {
            stmt.bindLong(2, rssi);
        }
 
        Long mac = entity.getMac();
        if (mac != null) {
            stmt.bindLong(3, mac);
        }
 
        Long advertisementMSB = entity.getAdvertisementMSB();
        if (advertisementMSB != null) {
            stmt.bindLong(4, advertisementMSB);
        }
 
        Long advertisementLSB = entity.getAdvertisementLSB();
        if (advertisementLSB != null) {
            stmt.bindLong(5, advertisementLSB);
        }
 
        Long bleuuidMSB = entity.getBleuuidMSB();
        if (bleuuidMSB != null) {
            stmt.bindLong(6, bleuuidMSB);
        }
 
        Long bleuuidLSB = entity.getBleuuidLSB();
        if (bleuuidLSB != null) {
            stmt.bindLong(7, bleuuidLSB);
        }
 
        Integer major = entity.getMajor();
        if (major != null) {
            stmt.bindLong(8, major);
        }
 
        Integer minor = entity.getMinor();
        if (minor != null) {
            stmt.bindLong(9, minor);
        }
 
        Integer txpower = entity.getTxpower();
        if (txpower != null) {
            stmt.bindLong(10, txpower);
        }
        stmt.bindLong(11, entity.getVolatility());
 
        Boolean ShareFlag = entity.getShareFlag();
        if (ShareFlag != null) {
            stmt.bindLong(12, ShareFlag ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BeaconData readEntity(Cursor cursor, int offset) {
        BeaconData entity = new BeaconData( //
            cursor.getLong(offset + 0), // TimeStamp
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // rssi
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // mac
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // advertisementMSB
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4), // advertisementLSB
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // bleuuidMSB
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // bleuuidLSB
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7), // major
            cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8), // minor
            cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9), // txpower
            cursor.getLong(offset + 10), // Volatility
            cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0 // ShareFlag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BeaconData entity, int offset) {
        entity.setTimeStamp(cursor.getLong(offset + 0));
        entity.setRssi(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setMac(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setAdvertisementMSB(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setAdvertisementLSB(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
        entity.setBleuuidMSB(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setBleuuidLSB(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setMajor(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
        entity.setMinor(cursor.isNull(offset + 8) ? null : cursor.getInt(offset + 8));
        entity.setTxpower(cursor.isNull(offset + 9) ? null : cursor.getInt(offset + 9));
        entity.setVolatility(cursor.getLong(offset + 10));
        entity.setShareFlag(cursor.isNull(offset + 11) ? null : cursor.getShort(offset + 11) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BeaconData entity, long rowId) {
        entity.setTimeStamp(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BeaconData entity) {
        if(entity != null) {
            return entity.getTimeStamp();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
