package ch.ethz.coss.nervousnet.vm.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ch.ethz.coss.nervousnet.vm.model.GyroData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "GYRO_DATA".
*/
public class GyroDataDao extends AbstractDao<GyroData, Long> {

    public static final String TABLENAME = "GYRO_DATA";

    /**
     * Properties of entity GyroData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property TimeStamp = new Property(0, long.class, "TimeStamp", true, "TIME_STAMP");
        public final static Property GyroX = new Property(1, Float.class, "GyroX", false, "GYRO_X");
        public final static Property GyroY = new Property(2, Float.class, "GyroY", false, "GYRO_Y");
        public final static Property GyroZ = new Property(3, Float.class, "GyroZ", false, "GYRO_Z");
        public final static Property Volatility = new Property(4, long.class, "Volatility", false, "VOLATILITY");
        public final static Property ShareFlag = new Property(5, Boolean.class, "ShareFlag", false, "SHARE_FLAG");
    };


    public GyroDataDao(DaoConfig config) {
        super(config);
    }
    
    public GyroDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"GYRO_DATA\" (" + //
                "\"TIME_STAMP\" INTEGER PRIMARY KEY NOT NULL ," + // 0: TimeStamp
                "\"GYRO_X\" REAL," + // 1: GyroX
                "\"GYRO_Y\" REAL," + // 2: GyroY
                "\"GYRO_Z\" REAL," + // 3: GyroZ
                "\"VOLATILITY\" INTEGER NOT NULL ," + // 4: Volatility
                "\"SHARE_FLAG\" INTEGER);"); // 5: ShareFlag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"GYRO_DATA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, GyroData entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTimeStamp());
 
        Float GyroX = entity.getGyroX();
        if (GyroX != null) {
            stmt.bindDouble(2, GyroX);
        }
 
        Float GyroY = entity.getGyroY();
        if (GyroY != null) {
            stmt.bindDouble(3, GyroY);
        }
 
        Float GyroZ = entity.getGyroZ();
        if (GyroZ != null) {
            stmt.bindDouble(4, GyroZ);
        }
        stmt.bindLong(5, entity.getVolatility());
 
        Boolean ShareFlag = entity.getShareFlag();
        if (ShareFlag != null) {
            stmt.bindLong(6, ShareFlag ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public GyroData readEntity(Cursor cursor, int offset) {
        GyroData entity = new GyroData( //
            cursor.getLong(offset + 0), // TimeStamp
            cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1), // GyroX
            cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2), // GyroY
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // GyroZ
            cursor.getLong(offset + 4), // Volatility
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // ShareFlag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, GyroData entity, int offset) {
        entity.setTimeStamp(cursor.getLong(offset + 0));
        entity.setGyroX(cursor.isNull(offset + 1) ? null : cursor.getFloat(offset + 1));
        entity.setGyroY(cursor.isNull(offset + 2) ? null : cursor.getFloat(offset + 2));
        entity.setGyroZ(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setVolatility(cursor.getLong(offset + 4));
        entity.setShareFlag(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(GyroData entity, long rowId) {
        entity.setTimeStamp(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(GyroData entity) {
        if(entity != null) {
            return entity.getTimeStamp();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
