package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LOCATION_READING".
 */
public class LocationReading extends SensorReading  {

    /** Not-null value. */
    private java.util.Date TimeStamp;
    private Double Latitude;
    private Double Longitude;
    private Double Altitude;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LocationReading() {
    }

    public LocationReading(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public LocationReading(java.util.Date TimeStamp, Double Latitude, Double Longitude, Double Altitude) {
        this.TimeStamp = TimeStamp;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
        this.Altitude = Altitude;
    }

    /** Not-null value. */
    public java.util.Date getTimeStamp() {
        return TimeStamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimeStamp(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public Double getLatitude() {
        return Latitude;
    }

    public void setLatitude(Double Latitude) {
        this.Latitude = Latitude;
    }

    public Double getLongitude() {
        return Longitude;
    }

    public void setLongitude(Double Longitude) {
        this.Longitude = Longitude;
    }

    public Double getAltitude() {
        return Altitude;
    }

    public void setAltitude(Double Altitude) {
        this.Altitude = Altitude;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
