package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MAGNETIC_DATA".
 */
public class MagneticData implements SensorDataImpl {

    private Long id;
    private Long TimeStamp;
    private Float MagX;
    private Float MagY;
    private Float MagZ;
    private long Volatility;
    private Boolean ShareFlag;

    // KEEP FIELDS - put your custom fields here
    private int type;
    // KEEP FIELDS END

    public MagneticData() {
    }

    public MagneticData(Long id) {
        this.id = id;
    }

    public MagneticData(Long id, Long TimeStamp, Float MagX, Float MagY, Float MagZ, long Volatility, Boolean ShareFlag) {
        this.id = id;
        this.TimeStamp = TimeStamp;
        this.MagX = MagX;
        this.MagY = MagY;
        this.MagZ = MagZ;
        this.Volatility = Volatility;
        this.ShareFlag = ShareFlag;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(Long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public Float getMagX() {
        return MagX;
    }

    public void setMagX(Float MagX) {
        this.MagX = MagX;
    }

    public Float getMagY() {
        return MagY;
    }

    public void setMagY(Float MagY) {
        this.MagY = MagY;
    }

    public Float getMagZ() {
        return MagZ;
    }

    public void setMagZ(Float MagZ) {
        this.MagZ = MagZ;
    }

    public long getVolatility() {
        return Volatility;
    }

    public void setVolatility(long Volatility) {
        this.Volatility = Volatility;
    }

    public Boolean getShareFlag() {
        return ShareFlag;
    }

    public void setShareFlag(Boolean ShareFlag) {
        this.ShareFlag = ShareFlag;
    }

    // KEEP METHODS - put your custom methods here
	@Override
	public Integer getType() {
		// TODO Auto-generated method stub
		return type;
	}

	@Override
	public void setType(Integer type) {
		// TODO Auto-generated method stub
		this.type = type;
	}
    // KEEP METHODS END

}
