package ch.ethz.coss.nervousnet.vm.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ch.ethz.coss.nervousnet.vm.model.SensorReading;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SENSOR_READING".
*/
public class SensorReadingDao extends AbstractDao<SensorReading, java.util.Date> {

    public static final String TABLENAME = "SENSOR_READING";

    /**
     * Properties of entity SensorReading.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Type = new Property(0, Integer.class, "Type", false, "TYPE");
        public final static Property TimeStamp = new Property(1, java.util.Date.class, "TimeStamp", true, "TIME_STAMP");
        public final static Property Volatility = new Property(2, long.class, "Volatility", false, "VOLATILITY");
        public final static Property ShareFlag = new Property(3, Boolean.class, "ShareFlag", false, "SHARE_FLAG");
    };


    public SensorReadingDao(DaoConfig config) {
        super(config);
    }
    
    public SensorReadingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SENSOR_READING\" (" + //
                "\"TYPE\" INTEGER," + // 0: Type
                "\"TIME_STAMP\" INTEGER PRIMARY KEY NOT NULL ," + // 1: TimeStamp
                "\"VOLATILITY\" INTEGER NOT NULL ," + // 2: Volatility
                "\"SHARE_FLAG\" INTEGER);"); // 3: ShareFlag
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SENSOR_READING\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, SensorReading entity) {
        stmt.clearBindings();
 
        Integer Type = entity.getType();
        if (Type != null) {
            stmt.bindLong(1, Type);
        }
        stmt.bindLong(2, entity.getTimeStamp().getTime());
        stmt.bindLong(3, entity.getVolatility());
 
        Boolean ShareFlag = entity.getShareFlag();
        if (ShareFlag != null) {
            stmt.bindLong(4, ShareFlag ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    public java.util.Date readKey(Cursor cursor, int offset) {
        return new java.util.Date(cursor.getLong(offset + 1));
    }    

    /** @inheritdoc */
    @Override
    public SensorReading readEntity(Cursor cursor, int offset) {
        SensorReading entity = new SensorReading( //
            cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0), // Type
            new java.util.Date(cursor.getLong(offset + 1)), // TimeStamp
            cursor.getLong(offset + 2), // Volatility
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0 // ShareFlag
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, SensorReading entity, int offset) {
        entity.setType(cursor.isNull(offset + 0) ? null : cursor.getInt(offset + 0));
        entity.setTimeStamp(new java.util.Date(cursor.getLong(offset + 1)));
        entity.setVolatility(cursor.getLong(offset + 2));
        entity.setShareFlag(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
     }
    
    /** @inheritdoc */
    @Override
    protected java.util.Date updateKeyAfterInsert(SensorReading entity, long rowId) {
        return entity.getTimeStamp();
    }
    
    /** @inheritdoc */
    @Override
    public java.util.Date getKey(SensorReading entity) {
        if(entity != null) {
            return entity.getTimeStamp();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
