package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "ACCEL_READING".
 */
public class AccelReading extends SensorReading  {

    /** Not-null value. */
    private java.util.Date TimeStamp;
    private Float X;
    private Float Y;
    private Float Z;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AccelReading() {
    }

    public AccelReading(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public AccelReading(java.util.Date TimeStamp, Float X, Float Y, Float Z) {
        this.TimeStamp = TimeStamp;
        this.X = X;
        this.Y = Y;
        this.Z = Z;
    }

    /** Not-null value. */
    public java.util.Date getTimeStamp() {
        return TimeStamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimeStamp(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public Float getX() {
        return X;
    }

    public void setX(Float X) {
        this.X = X;
    }

    public Float getY() {
        return Y;
    }

    public void setY(Float Y) {
        this.Y = Y;
    }

    public Float getZ() {
        return Z;
    }

    public void setZ(Float Z) {
        this.Z = Z;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
