package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "BATTERY_DATA".
 */
public class BatteryData implements SensorDataImpl {
	private Integer Type = 0;
    private long TimeStamp;
    private Float Percent;
    private Byte ChargingType;
    private Byte Health;
    private Float Temperature;
    private Integer Volt;
    private long Volatility;
    private Boolean ShareFlag;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BatteryData() {
    }

    public BatteryData(long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public BatteryData(long TimeStamp, Float Percent, Byte ChargingType, Byte Health, Float Temperature, Integer Volt, long Volatility, Boolean ShareFlag) {
        this.TimeStamp = TimeStamp;
        this.Percent = Percent;
        this.ChargingType = ChargingType;
        this.Health = Health;
        this.Temperature = Temperature;
        this.Volt = Volt;
        this.Volatility = Volatility;
        this.ShareFlag = ShareFlag;
    }

    public long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public Float getPercent() {
        return Percent;
    }

    public void setPercent(Float Percent) {
        this.Percent = Percent;
    }

    public Byte getChargingType() {
        return ChargingType;
    }

    public void setChargingType(Byte ChargingType) {
        this.ChargingType = ChargingType;
    }

    public Byte getHealth() {
        return Health;
    }

    public void setHealth(Byte Health) {
        this.Health = Health;
    }

    public Float getTemperature() {
        return Temperature;
    }

    public void setTemperature(Float Temperature) {
        this.Temperature = Temperature;
    }

    public Integer getVolt() {
        return Volt;
    }

    public void setVolt(Integer Volt) {
        this.Volt = Volt;
    }

    public long getVolatility() {
        return Volatility;
    }

    public void setVolatility(long Volatility) {
        this.Volatility = Volatility;
    }

    public Boolean getShareFlag() {
        return ShareFlag;
    }

    public void setShareFlag(Boolean ShareFlag) {
        this.ShareFlag = ShareFlag;
    }

    // KEEP METHODS - put your custom methods here

	@Override
	  public Integer getType() {
      return Type;
  }
	
	@Override
  public void setType(Integer Type) {
      this.Type = Type;
  }
    // KEEP METHODS END

}
