package ch.ethz.coss.nervousnet.vm.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ch.ethz.coss.nervousnet.vm.model.Config;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONFIG".
*/
public class ConfigDao extends AbstractDao<Config, Long> {

    public static final String TABLENAME = "CONFIG";

    /**
     * Properties of entity Config.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UUID = new Property(1, String.class, "UUID", false, "UUID");
        public final static Property DeviceBrand = new Property(2, String.class, "DeviceBrand", false, "DEVICE_BRAND");
        public final static Property DeviceModel = new Property(3, String.class, "DeviceModel", false, "DEVICE_MODEL");
        public final static Property DeviceOS = new Property(4, String.class, "DeviceOS", false, "DEVICE_OS");
        public final static Property DeviceOSversion = new Property(5, String.class, "DeviceOSversion", false, "DEVICE_OSVERSION");
        public final static Property LastSyncTime = new Property(6, java.util.Date.class, "LastSyncTime", false, "LAST_SYNC_TIME");
    };


    public ConfigDao(DaoConfig config) {
        super(config);
    }
    
    public ConfigDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONFIG\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"UUID\" TEXT," + // 1: UUID
                "\"DEVICE_BRAND\" TEXT," + // 2: DeviceBrand
                "\"DEVICE_MODEL\" TEXT," + // 3: DeviceModel
                "\"DEVICE_OS\" TEXT," + // 4: DeviceOS
                "\"DEVICE_OSVERSION\" TEXT," + // 5: DeviceOSversion
                "\"LAST_SYNC_TIME\" INTEGER);"); // 6: LastSyncTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONFIG\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Config entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String UUID = entity.getUUID();
        if (UUID != null) {
            stmt.bindString(2, UUID);
        }
 
        String DeviceBrand = entity.getDeviceBrand();
        if (DeviceBrand != null) {
            stmt.bindString(3, DeviceBrand);
        }
 
        String DeviceModel = entity.getDeviceModel();
        if (DeviceModel != null) {
            stmt.bindString(4, DeviceModel);
        }
 
        String DeviceOS = entity.getDeviceOS();
        if (DeviceOS != null) {
            stmt.bindString(5, DeviceOS);
        }
 
        String DeviceOSversion = entity.getDeviceOSversion();
        if (DeviceOSversion != null) {
            stmt.bindString(6, DeviceOSversion);
        }
 
        java.util.Date LastSyncTime = entity.getLastSyncTime();
        if (LastSyncTime != null) {
            stmt.bindLong(7, LastSyncTime.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Config readEntity(Cursor cursor, int offset) {
        Config entity = new Config( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // UUID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // DeviceBrand
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // DeviceModel
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // DeviceOS
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // DeviceOSversion
            cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)) // LastSyncTime
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Config entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUUID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDeviceBrand(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setDeviceModel(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDeviceOS(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDeviceOSversion(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLastSyncTime(cursor.isNull(offset + 6) ? null : new java.util.Date(cursor.getLong(offset + 6)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Config entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Config entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
