package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "HUMIDITY_DATA".
 */
public class HumidityData implements SensorDataImpl {
	private Integer Type = 0;
    private long TimeStamp;
    private Float Humidity;
    private long Volatility;
    private Boolean ShareFlag;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public HumidityData() {
    }

    public HumidityData(long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public HumidityData(long TimeStamp, Float Humidity, long Volatility, Boolean ShareFlag) {
        this.TimeStamp = TimeStamp;
        this.Humidity = Humidity;
        this.Volatility = Volatility;
        this.ShareFlag = ShareFlag;
    }

    public long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public Float getHumidity() {
        return Humidity;
    }

    public void setHumidity(Float Humidity) {
        this.Humidity = Humidity;
    }

    public long getVolatility() {
        return Volatility;
    }

    public void setVolatility(long Volatility) {
        this.Volatility = Volatility;
    }

    public Boolean getShareFlag() {
        return ShareFlag;
    }

    public void setShareFlag(Boolean ShareFlag) {
        this.ShareFlag = ShareFlag;
    }

    // KEEP METHODS - put your custom methods here
	@Override
	  public Integer getType() {
      return Type;
  }
	
	@Override
  public void setType(Integer Type) {
      this.Type = Type;
  }
    // KEEP METHODS END

}
