package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LIGHT_READING".
 */
public class LightReading extends SensorReading  {

    /** Not-null value. */
    private java.util.Date TimeStamp;
    private Float Lux;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LightReading() {
    }

    public LightReading(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public LightReading(java.util.Date TimeStamp, Float Lux) {
        this.TimeStamp = TimeStamp;
        this.Lux = Lux;
    }

    /** Not-null value. */
    public java.util.Date getTimeStamp() {
        return TimeStamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimeStamp(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public Float getLux() {
        return Lux;
    }

    public void setLux(Float Lux) {
        this.Lux = Lux;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
