package ch.ethz.coss.nervousnet.vm.model;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ch.ethz.coss.nervousnet.vm.model.LocationReading;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LOCATION_READING".
*/
public class LocationReadingDao extends AbstractDao<LocationReading, java.util.Date> {

    public static final String TABLENAME = "LOCATION_READING";

    /**
     * Properties of entity LocationReading.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property TimeStamp = new Property(0, java.util.Date.class, "TimeStamp", true, "TIME_STAMP");
        public final static Property Latitude = new Property(1, Double.class, "Latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(2, Double.class, "Longitude", false, "LONGITUDE");
        public final static Property Altitude = new Property(3, Double.class, "Altitude", false, "ALTITUDE");
    };


    public LocationReadingDao(DaoConfig config) {
        super(config);
    }
    
    public LocationReadingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LOCATION_READING\" (" + //
                "\"TIME_STAMP\" INTEGER PRIMARY KEY NOT NULL ," + // 0: TimeStamp
                "\"LATITUDE\" REAL," + // 1: Latitude
                "\"LONGITUDE\" REAL," + // 2: Longitude
                "\"ALTITUDE\" REAL);"); // 3: Altitude
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LOCATION_READING\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, LocationReading entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTimeStamp().getTime());
 
        Double Latitude = entity.getLatitude();
        if (Latitude != null) {
            stmt.bindDouble(2, Latitude);
        }
 
        Double Longitude = entity.getLongitude();
        if (Longitude != null) {
            stmt.bindDouble(3, Longitude);
        }
 
        Double Altitude = entity.getAltitude();
        if (Altitude != null) {
            stmt.bindDouble(4, Altitude);
        }
    }

    /** @inheritdoc */
    @Override
    public java.util.Date readKey(Cursor cursor, int offset) {
        return new java.util.Date(cursor.getLong(offset + 0));
    }    

    /** @inheritdoc */
    @Override
    public LocationReading readEntity(Cursor cursor, int offset) {
        LocationReading entity = new LocationReading( //
            new java.util.Date(cursor.getLong(offset + 0)), // TimeStamp
            cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1), // Latitude
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // Longitude
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3) // Altitude
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, LocationReading entity, int offset) {
        entity.setTimeStamp(new java.util.Date(cursor.getLong(offset + 0)));
        entity.setLatitude(cursor.isNull(offset + 1) ? null : cursor.getDouble(offset + 1));
        entity.setLongitude(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setAltitude(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected java.util.Date updateKeyAfterInsert(LocationReading entity, long rowId) {
        return entity.getTimeStamp();
    }
    
    /** @inheritdoc */
    @Override
    public java.util.Date getKey(LocationReading entity) {
        if(entity != null) {
            return entity.getTimeStamp();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
