package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MAGNETIC_DATA".
 */
public class MagneticData implements SensorDataImpl {
	private Integer Type = 0;
    private long TimeStamp;
    private Float MagX;
    private Float MagY;
    private Float MagZ;
    private long Volatility;
    private Boolean ShareFlag;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MagneticData() {
    }

    public MagneticData(long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public MagneticData(long TimeStamp, Float MagX, Float MagY, Float MagZ, long Volatility, Boolean ShareFlag) {
        this.TimeStamp = TimeStamp;
        this.MagX = MagX;
        this.MagY = MagY;
        this.MagZ = MagZ;
        this.Volatility = Volatility;
        this.ShareFlag = ShareFlag;
    }

    public long getTimeStamp() {
        return TimeStamp;
    }

    public void setTimeStamp(long TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public Float getMagX() {
        return MagX;
    }

    public void setMagX(Float MagX) {
        this.MagX = MagX;
    }

    public Float getMagY() {
        return MagY;
    }

    public void setMagY(Float MagY) {
        this.MagY = MagY;
    }

    public Float getMagZ() {
        return MagZ;
    }

    public void setMagZ(Float MagZ) {
        this.MagZ = MagZ;
    }

    public long getVolatility() {
        return Volatility;
    }

    public void setVolatility(long Volatility) {
        this.Volatility = Volatility;
    }

    public Boolean getShareFlag() {
        return ShareFlag;
    }

    public void setShareFlag(Boolean ShareFlag) {
        this.ShareFlag = ShareFlag;
    }

    // KEEP METHODS - put your custom methods here
	@Override
	  public Integer getType() {
      return Type;
  }
	
	@Override
  public void setType(Integer Type) {
      this.Type = Type;
  }
    // KEEP METHODS END

}
