package ch.ethz.coss.nervousnet.vm.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SENSOR_READING".
 */
public class SensorReading {

    private Integer Type;
    /** Not-null value. */
    private java.util.Date TimeStamp;
    private long Volatility;
    private Boolean ShareFlag;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public SensorReading() {
    }

    public SensorReading(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public SensorReading(Integer Type, java.util.Date TimeStamp, long Volatility, Boolean ShareFlag) {
        this.Type = Type;
        this.TimeStamp = TimeStamp;
        this.Volatility = Volatility;
        this.ShareFlag = ShareFlag;
    }

    public Integer getType() {
        return Type;
    }

    public void setType(Integer Type) {
        this.Type = Type;
    }

    /** Not-null value. */
    public java.util.Date getTimeStamp() {
        return TimeStamp;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimeStamp(java.util.Date TimeStamp) {
        this.TimeStamp = TimeStamp;
    }

    public long getVolatility() {
        return Volatility;
    }

    public void setVolatility(long Volatility) {
        this.Volatility = Volatility;
    }

    public Boolean getShareFlag() {
        return ShareFlag;
    }

    public void setShareFlag(Boolean ShareFlag) {
        this.ShareFlag = ShareFlag;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
